### ISSUE TITLE
Add copy password as image format

### ISSUE THREAD

**Issue by phamthai072** [combokitnet/combokitnet#1]
### What kind of request are you making?

A new feature for an existing tool

### Describe the feature you're proposing

Add copy password with image for can store with image format and can decode the password back.

### Have you seen something similar before?

https://xcode.darkbyte.ru/

### Before you submit

- [x] I've searched for existing issues to avoid duplicates.
- [X] I've confirmed that this feature isn't already in the project.

**Comment by combokitnet** [comment]
🚀 Feature Update: 'Copy Password as Image Format' has been successfully implemented! 🎉
You can now copy passwords as an image for enhanced flexibility and sharing.
Thank you for your support and suggestions!

<img width="1307" alt="image" src="https://github.com/user-attachments/assets/a0b09ddc-0ee2-42e2-8bae-f5d711d106b4" />
