### ISSUE TITLE
Password copy history

### ISSUE THREAD

**Issue by phamthai072** [combokitnet/combokitnet#2]
### What kind of request are you making?

A new feature for an existing tool

### Describe the feature you're proposing

show password copy history

**Comment by combokitnet** [comment]
<img width="1329" alt="image" src="https://github.com/user-attachments/assets/e511215f-9e24-4a96-9667-8614b9a32a01" />
🚀 Feature Update: 'Password Copy History' has been successfully implemented! 
Thank you for your feedback and patience. Happy password managing!
